// Package internalapi exposes the daemon's internal API surface that
// Job Pods call to authenticate, fetch their task context, and report
// progress (M2-T3, ADR-0008).
//
// The internal API lives at /internal/v1/ on the same loopback HTTP
// server that serves the M1 /projects/... and /jobs/... API. It is
// kept behind a bearer-token middleware: every request must carry
// Authorization: Bearer <token> matching the token issued for the
// job ID in the URL path. Tokens are 16-byte random hex strings
// generated by internal/jobpod (M2-T3 commit 1) and mounted into
// the pod at /run/athanor/token.
//
// The package has no dependency on internal/llm — the internal API
// serves the pod, not the model. Gate G2 enforces that.
package internalapi

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
)

// TokenStore is the surface the auth middleware reads. The production
// implementation is *jobpod.Manager (the in-memory map of
// podID→token); tests pass a fake.
type TokenStore interface {
	// Get returns the active token for jobID, or ErrTokenNotFound
	// if no active pod exists for that ID.
	Get(jobID string) (token string, err error)
}

// ErrTokenNotFound is returned by TokenStore.Get when no active
// pod is registered for the requested job ID.
var ErrTokenNotFound = errors.New("internalapi: no active token for job")

// ErrToolDisallowed is the sentinel handleExecuteCode and
// handleRunTests return (as a 403) when the per-job envelope
// does not include the requested tool. The handler is the only
// place this check runs; Gate G2's TestGateG2ToolEnvelopeBypassImpossible
// structurally proves every execute_code/run_tests route references
// the envelope lookup.
var ErrToolDisallowed = errors.New("internalapi: tool not in job envelope")

// writeJSON is the standard response writer: always JSON, UTF-8.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// writeError reports a JSON error body.
func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

// contextKey is unexported so other packages cannot collide with
// our context values.
type contextKey int

const (
	ctxKeyJobID contextKey = iota + 1
)

// jobIDFromContext returns the authenticated job ID stored on the
// request context by the auth middleware. It is the only safe way
// for handlers to learn which job the request is for; trusting the
// URL path inside the handler would defeat the URL-vs-token
// binding.
func jobIDFromContext(ctx context.Context) string {
	v, _ := ctx.Value(ctxKeyJobID).(string)
	return v
}
