-- Migration 0009: MCE chunk store + Dormant Index (ROADMAP M5-T2; ADR-0021).
--
-- §10.1 Full-Fidelity Division persists dormant chunks here. `context_chunks`
-- holds the byte-exact content of each chunk plus the metadata the Dormant
-- Index publishes (path, language, kind, byte range, line range). Chunk IDs
-- are deterministic content-derived handles (ADR-0021 §5) — sha256 of
-- source_hash || byte_start-byte_end, truncated — not the §5 entity UUIDs.
-- Re-ingesting an unchanged source therefore targets the same rows via
-- UNIQUE (source_hash, byte_start); a changed file yields a new source_hash
-- and new rows, leaving the old ones addressable until pruned.
--
-- `dormant_index` is 1:1 with `context_chunks` and carries the one-line
-- summary (§10.1) generated by the `wide` persona. `summary_status` is
-- 'pending' until the summarizer fills it; a summarizer failure leaves the
-- row 'pending' rather than losing the chunk (indexing is the §17 idle path).
--
-- `content` is a BLOB so reassembly is byte-identical without a second
-- storage tier (ADR-0021 §6). The division size caps
-- (division_max_source_bytes / division_max_chunk_bytes) bound the growth of
-- the single-connection database.
--
-- FK note (ADR-0006): the migration runner disables PRAGMA foreign_keys
-- around each migration and gates the commit on PRAGMA foreign_key_check, so
-- the dormant_index → context_chunks reference is safe to introduce here.

CREATE TABLE context_chunks (
    id             TEXT PRIMARY KEY,
    source_relpath TEXT NOT NULL,
    source_hash    TEXT NOT NULL,
    lang           TEXT NOT NULL,
    kind           TEXT NOT NULL CHECK (kind IN ('ast','structural','header','fallback')),
    byte_start     INTEGER NOT NULL,
    byte_end       INTEGER NOT NULL,
    line_start     INTEGER NOT NULL,
    line_end       INTEGER NOT NULL,
    content_hash   TEXT NOT NULL,
    content        BLOB NOT NULL,
    project_id     TEXT,
    job_id         TEXT,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (source_hash, byte_start)
);

CREATE INDEX idx_context_chunks_source  ON context_chunks(source_hash, byte_start);
CREATE INDEX idx_context_chunks_project ON context_chunks(project_id);

CREATE TABLE dormant_index (
    chunk_id       TEXT PRIMARY KEY REFERENCES context_chunks(id),
    summary        TEXT NOT NULL DEFAULT '',
    summary_status TEXT NOT NULL DEFAULT 'pending'
                   CHECK (summary_status IN ('pending','ready','failed')),
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX idx_dormant_index_status ON dormant_index(summary_status);

CREATE TRIGGER context_chunks_touch_updated_at AFTER UPDATE ON context_chunks
BEGIN
    UPDATE context_chunks SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER dormant_index_touch_updated_at AFTER UPDATE ON dormant_index
BEGIN
    UPDATE dormant_index SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE chunk_id = NEW.chunk_id;
END;