// Package egress is the §21.3 file-airlock egress pipeline
// (ROADMAP M4-T4; ADR-0015). It observes `artifact_accepted`
// events on the append-only event log, validates the
// artifact's exported tree through the path-containment
// library and the per-pipeline scanner registry, and
// copies a clean export to `workspace/exports/<project>/<artifact>-<sha12>/`.
//
// # Originals untouched (re-stated)
//
// The artifact is in the artifact store; this package
// reads from the store and writes to `exports/`. The
// source artifact is never modified.
//
// # Egress does NOT run prompt-injection scanners
//
// Per ADR-0015 §"Trust boundaries, not all text", the
// egress pipeline runs `size + zipbomb + clamav + yara`
// only. Prompt-injection scanning of egress bytes is a
// category error: egress data was generated by the LLM,
// not received from an untrusted source. The classifier
// for the high-leverage scanner (security-persona
// classifier, M4-T5) gates the LLM's *input*, not its
// output.
//
// # Idempotency
//
// The exporter uses the artifact's SHA-256 (passed via
// the audit event's data payload) as the export
// directory's suffix. Re-running the exporter on the
// same accepted artifact is a no-op: the export
// directory already exists with the same SHA-12 suffix;
// the audit row is `egress_unchanged` rather than
// `egress_complete`.
package egress
